CREATE TABLE Majors
(
MajorID INT IDENTITY PRIMARY KEY,
[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Students
(
StudentID INT IDENTITY PRIMARY KEY,
StudentNumber VARCHAR(10) NOT NULL,
StudentName VARCHAR(50) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
PaymentID INT IDENTITY PRIMARY KEY,
PaymentDate DATE,
PaymentAmount DECIMAL(15,2),
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects
(
SubjectID INT IDENTITY PRIMARY KEY,
SubjectName VARCHAR(50) NOT NULL,
)

CREATE TABLE Agenda 
(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID),
CONSTRAINT PK_Student_Subject PRIMARY KEY (StudentID, SubjectID)
)